server:
  error:
    include-message: always
    include-binding-errors: always
  port: 2222


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: Interview-Service
  main:
    allow-bean-definition-overriding: true
  datasource:
    password: 1403
    url: jdbc:mysql://localhost:3306/interviews
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    database: mysql