server:
  error:
    include-message: always
    include-binding-errors: always
  port: 1111


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: Auth-Service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/auth_users
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database: postgresql

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
gcp:
  firebase:
    service-account=classpath:firebase-service-account.json