server:
  port: 7777

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: Ath-Service
          uri: lb://Auth-Service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<s>.*), /${s}

        - id: Interview-Service
          uri: lb://Interview-Service
          predicates:
            - Path=/api/interview/**
          filters:
            - RewritePath=/api/interview/(?<s>.*), /${s}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-micro-services-realm



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

