server:
  port: 7777

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: Ath-Service
          uri: lb://Auth-Service
          predicates:
            - Path=/api/s1/**
          filters:
            - RewritePath=/(?<s>.*), /${s}

        - id: Interview-Service
          uri: lb://Interview-Service
          predicates:
            - Path=/api/s2/**
          filters:
            - RewritePath=/(?<s>.*), /${s}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

