server:
  port: 7777

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/api/auth-service/**
          filters:
            - RewritePath=/api/auth-service/(?<s>.*), /${s}
          uri: lb://Auth-Service
        - id: route2
          predicates:
            - Path=/interview-service/**
          filters:
            - RewritePath=/interview-service/(?<s>.*), /${s}
          uri: lb://Interview-Service