
server:
  port: 7777


spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: route1
          predicates:
            - Path=/api/auth-service/**
          filters:
            - RewritePath=/api/auth-service/(?<s>.*), /${s}
          uri: lb://Auth-Service
        - id: route2
          predicates:
            - Path=/api/interview-service/**
          filters:
            - RewritePath=/api/interview-service/(?<s>.*), /${s}
          uri: lb://Interview-Service

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
        ignoreExceptions:
          - java.lang.IllegalStateException
        shared:
          slidingWindowSize: 100
          permittedNumberOfCallsInHalfOpenState: 30
          waitDurationInOpenState: 1s
          failureRateThreshold: 50
          eventConsumerBufferSize: 10
          ignoreExceptions:
            - java.lang.IllegalStateException
timelimiter:
  configs:
    default:
      timeoutDuration: 10s
      cancelRunningFuture: false
instances:
  backendB:
    timeoutDuration: 250ms

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
