
spring:
  application:
    name: registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888